<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="protobuf-net" Version="3.2.26" />
    <PackageReference Include="Svg" Version="3.4.4" />
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\common\Netsoftware.Xanthos.Common.Resources\Netsoftware.Xanthos.Common.Resources.csproj" />
    <ProjectReference Include="..\Netsoftware.Xanthos.Database\Netsoftware.Xanthos.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dto\" />
    <Folder Include="Extensions\" />
    <Folder Include="Resources\" />
  </ItemGroup>

</Project>
