<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Netsoftware.Xanthos.Common.UrlTokenGenerator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="6.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="6.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="6.0.20" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="key-19bd143a-f2ae-4cee-b20b-e54a62a90b9d.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>