before_script:
  - |
    if [[ -f "deploy/settings-branch-${CI_COMMIT_REF_NAME}/.env" ]]; then
        source "deploy/settings-branch-${CI_COMMIT_REF_NAME}/.env"
    fi
    
stages:
- build
- deploy

build-mobile-app:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0
  tags:
  - shared_docker
  only:
    refs:
      - master
  script: 
    - sed -i -e "s#CONNECTION_STRING#$AFMULTISELECTOR_DB#g" AF_mobile_web_api/appsettings.Production.json;
    - dotnet publish -c Release -o deploy/template/mobile-api/build
  artifacts:
    paths:
      - $PWD/deploy/template/mobile-api/build
    expire_in: 2 days
    expose_as: 'af-mobile-net'
    
deploy:
    stage: deploy
    image: ubuntu
    tags:
    - shared_docker
    only:
      refs:
        - master
    needs:
        - build-mobile-app
    script:
        - apt-get update && apt-get install -y --no-install-recommends sed ssh rsync
        - cp $NESTOYA_DEV_PRIVATE_KEY pkey
        - chmod 600 pkey
        - mkdir -p ~/.ssh/
        - ssh-keyscan $NESTOYA_DEV_SSH_URL >> ~/.ssh/known_hosts
        - chmod +x deploy/template/mobile-api/start.sh
        - rsync -av --force -e "ssh -i pkey" deploy/template/. deploy@$NESTOYA_DEV_SSH_URL:/home/deploy/$DEPLOY_DIR/.
        - ssh -i pkey deploy@$NESTOYA_DEV_SSH_URL /home/deploy/$DEPLOY_DIR/mobile-api/start.sh
