<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Netsoftware.Xanthos.ApplicationInstance.Infrastructure\Netsoftware.Xanthos.ApplicationInstance.Infrastructure.csproj" />
  </ItemGroup>

</Project>
