    <Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <UserSecretsId>dda8fba0-c8ff-49f6-b1f9-a42ad78464b5</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Helpers\**" />
    <Content Remove="Helpers\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <None Remove="Helpers\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.20" />
     <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.18.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.5.0" />
    <PackageReference Include="Gelf.Extensions.Logging" Version="2.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\common\Netsoftware.Xanthos.Common.CustomAuthenticationMiddleware\Netsoftware.Xanthos.Common.AuthenticationMiddleware.csproj" />
    <ProjectReference Include="..\common\Netsoftware.Xanthos.Common.CustomAuthorizationHeaderProviderMiddleware\Netsoftware.Xanthos.Common.AuthorizationHeaderProviderMiddleware.csproj" />
    <ProjectReference Include="..\common\Netsoftware.Xanthos.Common.EmailSender\Netsoftware.Xanthos.Common.EmailSender.csproj" />
    <ProjectReference Include="..\common\Netsoftware.Xanthos.Common.HttpClient\Netsoftware.Xanthos.Common.HttpClient.csproj" />
    <ProjectReference Include="..\common\Netsoftware.Xanthos.Common.Internationalities\Netsoftware.Xanthos.Common.Internationalities.csproj" />
    <ProjectReference Include="..\common\Netsoftware.Xanthos.Common.Resources\Netsoftware.Xanthos.Common.Resources.csproj" />
    <ProjectReference Include="..\common\Netsoftware.Xanthos.Common.DatabaseConfiguration\Netsoftware.Xanthos.Common.DatabaseConfiguration.csproj" />
    <ProjectReference Include="..\Netsoftware.Xanthos.ApplicationInstance.Api\Netsoftware.Xanthos.ApplicationInstance.Api.csproj" />
    <ProjectReference Include="..\Netsoftware.Xanthos.Database\Netsoftware.Xanthos.Database.csproj" />
    <ProjectReference Include="..\Netsoftware.Xanthos.EmailQueue.Api\Netsoftware.Xanthos.EmailQueue.Api.csproj" />
    <ProjectReference Include="..\Netsoftware.Xanthos.EmailQueue.HostService\Netsoftware.Xanthos.EmailQueue.HostService.csproj" />
    <ProjectReference Include="..\Netsoftware.Xanthos.Infrastructure\Netsoftware.Xanthos.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Netsoftware.Xanthos.Api.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>  
  </ItemGroup>
  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>
</Project>
