<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Netsoftware.Xanthos.Database\Netsoftware.Xanthos.Database.csproj" />
    <ProjectReference Include="..\Netsoftware.Xanthos.EmailQueue.Database\Netsoftware.Xanthos.EmailQueue.Database.csproj" />
  </ItemGroup>

</Project>
