<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.1.0" />
    <PackageReference Include="RazorEngine.NetCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="7.0.0" />
    <PackageReference Include="RazorLight.NetCore3" Version="3.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Netsoftware.Xanthos.Common.HttpClient\Netsoftware.Xanthos.Common.HttpClient.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="EmailTemplates\**\*.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>